### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by AntoniRomera** [gcartlidge/biostarPython#1]
We are currently downloading from the BioStart web service the ".csv" file of the workers' markings and then importing it into our application.

Example:
Date;Device ID;Device;Device;User;Event;CP Key
26/04/2023 16:42;540099692;LPU2-RE - BioStation L2 540099692;;Biostar connected;
04/26/2023 16:40;540099692;LPU2-RE - BioStation L2 540099692;;Device Initiated;
04/26/2023 16:33;540099760;LPU1 - BioStation L1 540099760;36(Worker Name);Authentication 1:N correct (Fingerprint);Code2(Exit).

We would like to know if there is a method in the current library for with a query via GET/POST we can download the same information and avoid the 2 manual steps.

**Comment by gcartlidge** [comment]
Hi Antoni,

The above package is used to interface with our gSDK via python, for the BioStar 2 API, you can view the swagger of that from [https://127.0.0.1/swagger/index.html](https://127.0.0.1/swagger/index.html) from the BioStar 2 server. Anything you can do via the BioStar 2 UI, you can do via an API (BioStar 2 uses the APIs itself within its UI) (There is also another document at [bs2api.biostar2.com](bs2api.biostar2.com) ).

For the above Date-DeviceID-Device-User-Event-CP Key, are you using the monitoring section to get the data? If so, this API would be the /api/events/search API , You can also actually download the exported CSV automatically too [Detailed Here](https://bs2api.biostar2.com/#6495f56c-cea9-4124-aa13-700d33344961) , although it may be easier taking it directly from the JSON of the above API [Detailed here](https://bs2api.biostar2.com/#95c58101-69b4-45ab-b12d-d3b389964075).

If using the TnA section, this would be a seperate API, if you can email tech_uk@supremainc.com , we'll be able to help a bit more in depth with TnA.

**Comment by AntoniRomera** [comment]
Another question, is it possible to do server matching with face authentication?

**Comment by gcartlidge** [comment]
Currently, Face authentication via server matching is not supported with BioStar 2, Only fingerprint currently.
